# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'

# Commandline tools
brew "gh"
brew "git"
brew "mas" # Mac App Store Manager
brew "ripgrep"
brew "stow"

# Terminal
cask "iterm2"

# Programming languages
brew "julia"
brew "python@3.11"
# The r cask includes more of the system dependencies and by default installs
# binary r packages rather than from source
cask "r"
brew "rust"

# Editors/IDE
brew "neovim"
cask "rstudio"

# OS tools
cask "rectangle"

# Brower
cask "brave-browser"

# Fonts
cask "font-fira-code"

# Stuff from app store
mas 'Giphy Capture', id: 668208984

